---
title: "Sentiment analysis"
author: "Madeline Lui"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
library(tidyverse)
library(tidytext)
library(janeaustenr)
library(stringr)
library(tidytext)
library(tidyr)
library(reshape2)
library(wordcloud)
sentiments
```

```{r lexicon retrieval}
get_sentiments("bing")
```

```{r tidy dat}
tidy_dat <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]", 
                          ignore_case = TRUE)))) %>%
ungroup() %>%
  unnest_tokens(word, text)
```

```{r senti anal mod}
pos_senti <- get_sentiments("bing")%>%
  filter(sentiment == "positive")

tidy_dat %>%
  filter(book == "Pride & Prejudice") %>%
  semi_join(positive_senti) %>%
  count(word, sort=TRUE)
```

```{r pos and neg}
bing <- get_sentiments("bing")
PnP_senti <- tidy_dat %>%
  inner_join(bing) %>%
  count(book = "Pride & Prejudice", index=linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill=0) %>%
  mutate(sentiment = positive - negative)
```

```{r visualisation}
PnP_senti %>%
  ggplot(aes(x=index, y=sentiment, fill=book))+
  geom_bar(stat="identity", show.legend=TRUE)+
  labs(x="Index", y="Sentiment Score", fill="Book")+
  facet_wrap(~book, ncol = 2, scales = "free_x")+
  theme_minimal()
```

```{r word count frq}
word_count <- tidy_dat %>%
 inner_join(bing) %>%
 count(word, sentiment, sort = TRUE)
head(word_count)
```

```{r word count vis}
word_count %>%
 filter(n > 150) %>%
 mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
 mutate(word = reorder(word, n)) %>%
 ggplot(aes(word, n, fill = sentiment))+
 geom_col() +
 coord_flip() +
 labs(y = "Sentiment Score")+
  theme_light()
```

```{r wordcloud vis }
tidy_dat %>%
 inner_join(bing) %>%
 count(word, sentiment, sort = TRUE) %>%
 acast(word ~ sentiment, value.var = "n", fill = 0) %>%
 comparison.cloud(colors = c("violet", "salmon"),
          max.words = 100)
```